# Intermediat Neural Network In TensorFlow

### Load Dependencies

In [4]:
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt

### Load Data

In [5]:
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

### Preprocess Data

In [6]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_valid = X_valid.reshape(10000, 784).astype('float32')

In [8]:
X_train /= 255
X_valid /= 255

In [10]:
X_valid[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [11]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_valid = to_categorical(y_valid, n_classes)

In [12]:
y_valid[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

### Design Neural Network Architecture

In [13]:
model = Sequential()

#hidden layer
model.add(Dense(64, activation='relu', input_shape=(784, )))
model.add(Dense(64, activation='relu'))

#Output layer
model.add(Dense(10, activation='softmax'))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                50240     
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 10)                650       
                                                                 
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


### Configure Model 

In [27]:
# N.B.: learning rate is order of magnitude quicker relative to shallow net
model.compile(loss='categorical_crossentropy', optimizer=SGD(learning_rate=0.1), metrics=['accuracy'])

### Train !

In [28]:
# N.B.: number of epochs is order of magnitude smaller relative to shallow net
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/20
469/469 [==============================] - 6s 9ms/step - loss: 0.4867 - accuracy: 0.8586 - val_loss: 0.2577 - val_accuracy: 0.9233
Epoch 2/20
469/469 [==============================] - 4s 8ms/step - loss: 0.2299 - accuracy: 0.9333 - val_loss: 0.2134 - val_accuracy: 0.9347
Epoch 3/20
469/469 [==============================] - 4s 8ms/step - loss: 0.1803 - accuracy: 0.9465 - val_loss: 0.1683 - val_accuracy: 0.9483
Epoch 4/20
469/469 [==============================] - 4s 8ms/step - loss: 0.1500 - accuracy: 0.9557 - val_loss: 0.1477 - val_accuracy: 0.9541
Epoch 5/20
469/469 [==============================] - 5s 11ms/step - loss: 0.1282 - accuracy: 0.9618 - val_loss: 0.1237 - val_accuracy: 0.9608
Epoch 6/20
469/469 [==============================] - 4s 9ms/step - loss: 0.1115 - accuracy: 0.9674 - val_loss: 0.1295 - val_accuracy: 0.9596
Epoch 7/20
469/469 [==============================] - 4s 8ms/step - loss: 0.0988 - accuracy: 0.9710 - val_loss: 0.1090 - val_accuracy: 0.9672
Epoch

### Evaluating Model Performance

In [29]:
model.evaluate(X_valid, y_valid)

313/313 [==============================] - 1s 4ms/step - loss: 0.0820 - accuracy: 0.9751


[0.0819738432765007, 0.9750999808311462]

### Performing Inference

In [30]:
valid_0 = X_valid[0].reshape(1, 784)

In [31]:
model.predict(valid_0)

1/1 [==============================] - 0s 202ms/step


array([[4.2321180e-06, 5.7472243e-07, 3.0756313e-05, 8.1568788e-04,
        5.9799866e-11, 1.0571490e-06, 3.5619380e-10, 9.9913871e-01,
        5.5072765e-06, 3.4077314e-06]], dtype=float32)

In [32]:
import numpy as np

In [33]:
np.argmax(model.predict(valid_0), axis=1)

1/1 [==============================] - 0s 59ms/step


array([7], dtype=int64)