# Regression Example in TensorFlow

Predicting house prices in Bostom , Massachusetts

### Load Dependencies

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing # new!
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint # new!
import os # new!

### Load Data

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57026/57026 [==============================] - 0s 3us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

### Design Neural Network Architecture

In [7]:
model = Sequential()

# first hidden layer 
model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

# Second hidden layer:
model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

# Ouput layer:
model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (BatchN  (None, 32)               128       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Batc  (None, 16)               64        
 hNormalization)                                                 
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

### Configure Model 

In [9]:
model.compile(loss='mean_squared_error', optimizer='nadam')

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_basline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5' , # decimal integers
                                 save_weights_only=True)

### Train !

In [15]:
model.fit(X_train, y_train, 
         batch_size=8,
         epochs=32, 
         verbose=1, 
         validation_data=(X_valid, y_valid),
         callbacks=[modelcheckpoint]) # val loss below 50 is good, 40 great

Epoch 1/32
51/51 [==============================] - 0s 7ms/step - loss: 512.5151 - val_loss: 694.2935
Epoch 2/32
51/51 [==============================] - 0s 6ms/step - loss: 477.4895 - val_loss: 561.8386
Epoch 3/32
51/51 [==============================] - 0s 9ms/step - loss: 447.7862 - val_loss: 573.4167
Epoch 4/32
51/51 [==============================] - 0s 7ms/step - loss: 412.5865 - val_loss: 574.2456
Epoch 5/32
51/51 [==============================] - 0s 7ms/step - loss: 378.2771 - val_loss: 527.7382
Epoch 6/32
51/51 [==============================] - 0s 7ms/step - loss: 335.2429 - val_loss: 547.8359
Epoch 7/32
51/51 [==============================] - 1s 11ms/step - loss: 301.0364 - val_loss: 530.2228
Epoch 8/32
51/51 [==============================] - 0s 6ms/step - loss: 259.7699 - val_loss: 288.7511
Epoch 9/32
51/51 [==============================] - 0s 7ms/step - loss: 222.0566 - val_loss: 366.3605
Epoch 10/32
51/51 [==============================] - 0s 7ms/step - loss: 183.4627

### Performing Inference

In [17]:
model.load_weights(output_path + '/weights.28.hdf5')

In [18]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [19]:
y_valid[42]

14.1

In [20]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 [==============================] - 0s 389ms/step


array([[20.44919]], dtype=float32)